#! /bin/bash

cmd="--build"
if [[ "${#}" -eq "1" ]]; then
    if [[ "${1}" == --* ]]; then
        cmd=$1
    fi
fi

case "${cmd}" in
    --build|--package)
        mvn test || exit 1
        ;;
    --clean)
        mvn clean
        rm -rf target
        ;;
    --help)
        "Usage: ${0} [--build|--clean]"
        ;;
esac
