#! /bin/bash

# normalize work directory
wd=`dirname "$0"`
wd=`cd "$wd"; pwd`


cmd="--build"
if [[ "${#}" -eq "1" ]]; then
    if [[ "${1}" == --* ]]; then
        cmd=$1
    fi
fi


dest=../../build/transforms/coclustering
case "${cmd}" in
    --build)
        mvn assembly:assembly || exit 1
        mkdir -p $dest
        cp target/grouperfish-*.jar $dest/
        cp ./src/main/pig/* $dest/
        cp ./coclustering $dest/
        cp ./src/main/python/cocluster.py $dest/
        # TODO: move the (job) jars into the right place
        ;;
    --clean)
        mvn clean
        rm -r "${dest}"
        ;;
    --help)
        "Usage: ${0} [--build|--clean]"
        ;;
    *)
        "Usage: ${0} [--build|--clean]"
        exit 1
        ;;
esac
