#! /bin/bash

# normalize work directory
wd=`dirname "$0"`
wd=`cd "$wd"; pwd`


cmd="--build"
if [[ "${#}" -eq "1" ]]; then
    if [[ "${1}" == --* ]]; then
        cmd=$1
    fi
fi

build() {
    mvn install || exit 1
    mkdir -p ../build/lib ../build/conf ../build/bin
    cp target/grouperfish-service-*.jar ../build/lib/
    cp conf/* ../build/conf/
    cp bin/grouperfish ../build/bin/
}

package() {
    mvn dependency:copy-dependencies || exit 1
    cp target/lib/* ../build/lib
}


case "${cmd}" in
    --build)
        build
        ;;
    --package)
        build
        package
        ;;
    --clean)
        mvn clean
        rm -f ../build/lib/grouperfish-service-*
        rm -f ../build/bin/grouperfish
        ;;
    --help)
        "Usage: ${0} [--build|--clean]"
        ;;
esac
