#! /bin/bash

# normalize work directory
wd=`dirname "$0"`
wd=`cd "$wd"; pwd`

cmd="--build"
if [[ "${#}" -eq "1" ]]; then
    if [[ "${1}" == --* ]]; then cmd=$1; fi
fi

dest=../../build/tools/firefox_input/
case "${cmd}" in
    --build)
        mvn install || exit 1
        mkdir -p "${dest}/lib"
        cp target/grouperfish-*.jar "${dest}/lib/"
        cp bin/* "${dest}/"
        ;;
    --clean)
        mvn clean
        rm -r "${dest}"
        ;;
    --help)
        "Usage: ${0} [--build|--clean]"
        ;;
esac
