#! /bin/bash

# normalize work directory
wd=`dirname "$0"`
wd=`cd -P "$wd"; pwd`


# Load Firefox Input opinions into Grouperfish.

self="${0}"
usage() {
    echo "Usage: ${self} [http://grouperfish:port] namespace"
    echo
    echo "Reads opinion data from standard input and loads it into the"
    echo "given namespace."
    echo
}

cp_add_dir() {
    d="${1}"
    for lib in `find "${d}" -type f -name '*.jar'`; do
        CLASSPATH=${CLASSPATH}:"${lib}"
    done
}


tool=`dirname "$self"`

LOGBACK_OPTS=-Dlogback.configurationFile=logback-stdout.xml

load() {
    if [ -d $tool/target ]; then
        # we are on source tree
        grouperfish_home="${tool}/../../build"
        cp_add_dir "${tool}/target"
    else
        # we are on build tree
        grouperfish_home="${tool}/../.."
        cp_add_dir "${tool}/lib"
    fi

    cp_add_dir "${grouperfish_home}/lib"
    echo "CP $CLASSPATH"

    main=com.mozilla.grouperfish.tools.firefox_input.OpinionLoader
    java -cp $CLASSPATH $LOGBACK_OPTS ${main} $@
}

case "${1}" in
    --help)
        usage
        ;;
    *)
        load $@
esac
