package com.mozilla.grouperfish.batch;


/**
 * Describes how a task failed. Generated by handlers.
 * This information should be made available somehow under the run resource.
 */
public class Fail extends Exception {

    private static final long serialVersionUID = 0;

    private final Task task;

    public Fail(final Task task, final String message) {
        super(String.format("Task %s failed. %s", task, message));
        this.task = task;
    }

    public Fail(final Task task, final String message, final Throwable cause) {
        super(message, cause);
        this.task = task;
    }

    public Task task() {
        return task;
    }

    /**
     * Handlers can throw a hard failure if they are fairly certain that
     * retrying will not help.
     */
    public static final class HardFail extends Fail {
        public HardFail(final Task task, final String message, final Throwable cause) {
            super(task, message, cause);
        }

        public HardFail(final Task task, final String message) {
            super(task, message);
        }

        private static final long serialVersionUID = 1L;
    }


    /**
     * Handlers can throw a soft failure if they think that
     * retrying might help.
     */
    public static final class SoftFail extends Fail {
        public SoftFail(final Task task, final String message, final Throwable cause) {
            super(task, message, cause);
        }

        public SoftFail(final Task task, final String message) {
            super(task, message);
        }

        private static final long serialVersionUID = 1L;
    }
}
